### ISSUE TITLE
Meteor module.runSetters(...) is not recognized by Meteor-Vite

### ISSUE THREAD

**Issue by ouya99** [JorgenVatle/meteor-vite#26] opened 2023-09-04 14:50 UTC
Hello,

i am getting

(STDERR) "Meteor module.runSetters(...) is not recognized by Meteor-Vite! Please open an issue to get this resolved!"

when launching meteor with this package. It tells me to open an issue. so here you go :)

**Comment by JorgenVatle** [comment] 2023-09-07 00:33
Aha! Thank you for letting me know. I'll have that addressed shortly. This warning message should be safe to ignore. It's meant primarily to give a heads up in cases where an incompatible version of Meteor is in use. 😄

**Comment by ouya99** [comment] 2023-09-07 00:40
Thanks for your reply. Unfortunately i still did not manage to get it going. 
types are not found (like the ones from react-meteor-data). some packages are just not listed in .meteor/local/types

<img width="1199" alt="Screenshot 2023-09-07 at 02 39 22" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/151f8085-53db-4d6e-aa84-739adf479c54">

**Comment by JorgenVatle** [comment] 2023-09-07 01:01
I see! 🤔

Would you be able to provide me with an example project that replicates the issue, or possibly a list of packages for your project in case you don't have the time to set up a repo? 🙏

**Comment by ouya99** [comment] 2023-09-07 06:49
could you try with react-meteor-data? its one of many that does not work.

**Comment by JorgenVatle** [comment] 2023-09-07 13:25
Looks like Meteor-Vite is unable to detect `react-meteor-data` as a lazy-loaded package.

Adding `import 'meteor/react-meteor-data';` to your Meteor entrypoint file should resolve the issue for you until I have a fix in place.

**Comment by JorgenVatle** [comment] 2023-09-07 13:26
Could you list the other packages that aren't working for you so I have something to test against?

**Comment by ouya99** [comment] 2023-09-07 16:17
i added "import 'meteor/react-meteor-data';" in main.ts , yet still same error

in screenshot you see those modules that are found (maybe it only finds those with a index.ts file - types description file)

<img width="1031" alt="Screenshot 2023-09-07 at 18 16 40" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/99e94a5f-3710-4476-adc9-3590955cd402">

**Comment by ouya99** [comment] 2023-09-07 16:18
<img width="958" alt="Screenshot 2023-09-07 at 18 18 02" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/e2451b27-59f2-40de-ac23-395886c6185b">

**Comment by ouya99** [comment] 2023-09-07 16:52
[log.txt](https://github.com/JorgenVatle/meteor-vite/files/12551644/log.txt)

now some new errors. do not know what i changed though, tried to just replicate error

**Comment by JorgenVatle** [comment] 2023-09-07 17:58
Shipping a patch now which should resolve this issue for you. The package should also be automatically pulled into your main module following the update. 👍

**Comment by ouya99** [comment] 2023-09-07 18:07
I20230907-20:06:02.437(2)? 8:06:02 PM [vite] page reload imports/startup/both/i18n.js
I20230907-20:06:02.437(2)? 8:06:02 PM [vite] page reload imports/startup/client/index.jsx
I20230907-20:06:02.437(2)? 8:06:02 PM [vite] vite.config.ts changed, restarting server...
I20230907-20:06:02.662(2)? 8:06:02 PM [vite] server restarted.
W20230907-20:06:17.677(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:17.731(2)? (STDERR) 8:06:17 PM [vite] Internal server error: The "path" argument must be of type string. Received undefined
W20230907-20:06:17.732(2)? (STDERR)       at new NodeError (internal/errors.js:322:7)
W20230907-20:06:17.732(2)? (STDERR)       at validateString (internal/validators.js:124:11)
W20230907-20:06:17.732(2)? (STDERR)       at Object.join (path.js:1148:7)
W20230907-20:06:17.732(2)? (STDERR)       at Function.loadFileData (file:///Users/ouya/dev/webapp-webapp/node_modules/meteor-vite/dist/bin/worker/index.mjs:1308:26)
W20230907-20:06:17.732(2)? (STDERR)       at Function.prepareContext (file:///Users/ouya/dev/webapp-webapp/node_modules/meteor-vite/dist/bin/worker/index.mjs:1273:23)
W20230907-20:06:17.732(2)? (STDERR)       at Object.setupContext (file:///Users/ouya/dev/webapp-webapp/node_modules/meteor-vite/dist/bin/worker/index.mjs:1429:30)
W20230907-20:06:17.732(2)? (STDERR)       at Context.load (file:///Users/ouya/dev/webapp-webapp/node_modules/meteor-vite/dist/bin/worker/index.mjs:1483:38)
W20230907-20:06:17.732(2)? (STDERR)       at Object.load (file:///Users/ouya/dev/webapp-webapp/node_modules/vite/dist/node/chunks/dep-df561101.js:44254:64)
W20230907-20:06:17.732(2)? (STDERR)       at runMicrotasks (<anonymous>)
W20230907-20:06:17.732(2)? (STDERR)       at processTicksAndRejections (internal/process/task_queues.js:95:5)
W20230907-20:06:17.732(2)? (STDERR)       at async loadAndTransform (file:///Users/ouya/dev/webapp-webapp/node_modules/vite/dist/node/chunks/dep-df561101.js:54878:24)
W20230907-20:06:17.732(2)? (STDERR)       at async viteTransformMiddleware (file:///Users/ouya/dev/webapp-webapp/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)
W20230907-20:06:17.816(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:17.817(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:17.817(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:17.936(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:17.936(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:18.183(2)? (STDERR) The "path" argument must be of type string. Received undefined
W20230907-20:06:18.184(2)? (STDERR) The "path" argument must be of type string. Received undefined

**Comment by JorgenVatle** [comment] 2023-09-07 18:08
Oops, didn't mean to close it just yet. 😅

Let me know how it goes for you with the patch. 🤞

**Comment by JorgenVatle** [comment] 2023-09-07 18:12
> (STDERR) The "path" argument must be of type string. Received undefined

I believe that error there is caused by a mismatch between the Atmosphere package `jorgenvatle:vite-bundler` and the npm package `meteor-vite`.

Can you double check for me which version of the vite-bundler you're on?

**Comment by ouya99** [comment] 2023-09-07 18:18
1.2.1

same error, i just did download it 2 weeks ago, so never used older version than 1.2.1

**Comment by JorgenVatle** [comment] 2023-09-07 18:23
Aha. You will have to use `jorgenvatle:vite-bundler@1.3.2`

**Comment by ouya99** [comment] 2023-09-07 18:29
i rm the package and then tried to install 1.3.2

 meteor add jorgenvatle:vite-bundler@1.3.2
 => Errors while adding packages:             
                                              
While selecting package versions:
error: No version of jorgenvatle:vite-bundler satisfies all constraints: @1.3.2, @=1.2.1
Constraints on package "jorgenvatle:vite-bundler":
* jorgenvatle:vite-bundler@1.3.2 <- top level
* jorgenvatle:vite-bundler@=1.2.1 <- top level

**Comment by JorgenVatle** [comment] 2023-09-07 19:07
What do you get if you run `$ meteor list`?

**Comment by ouya99** [comment] 2023-09-07 19:21
meteor list
accounts-password                 2.3.4  Password support for accounts
alanning:roles                    3.5.1  Authorization package for Meteor
aldeed:collection2                3.5.0  Automatic validation of Meteor Mongo insert and update operations on the client and server
browser-policy                    1.1.2  Configure security policies enforced by the browser
check                             1.3.2  Check whether a value matches a pattern
ddp-server                        2.6.2  Meteor's latency-compensated distributed data server
dev-error-overlay                 0.1.2  Show build errors in client when using HMR
didericis:callpromise-mixin       0.0.1  A mixin for the mdg:validated-method package that adds a callPromise method
ecmascript                        0.16.7  Compiler plugin that supports ES2015+ in all .js files
email                             2.2.5  Send email messages
es5-shim                          4.8.0  Shims and polyfills to improve ECMAScript 5 support
fortawesome:fontawesome           4.7.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
fourseven:scss                    4.15.0  Style with attitude. Sass and SCSS support for Meteor.js.
johanbrook:publication-collector  1.1.0  Test a Meteor publication by collecting its output.
lacosta:method-hooks              1.5.4  Provide before and after hooks to methods created via mdg:validated-method
matb33:collection-hooks           1.2.2  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
mdg:validated-method              1.3.0  A simple wrapper for Meteor.methods
meteor-base                       1.5.1  Packages that every Meteor app needs
meteorhacks:aggregate             1.3.0  Proper MongoDB aggregations support for Meteor
meteortesting:mocha               2.1.0  Run Meteor package or app tests with Mocha
mizzao:user-status                1.0.1  User connection and idle state tracking for Meteor
mobile-experience                 1.1.0  Packages for a great mobile user experience
mongo                             1.16.7  Adaptor for using MongoDB and Minimongo over DDP
montiapm:agent                    2.47.3  Performance Monitoring for Meteor
montiapm:debug                    3.4.0  Full Stack Debugging Solution for Meteor
npdev:react-loadable              1.0.0  A React component for easy code splitting with Meteor's dynamic-import
ostrio:files                      2.3.3  Upload files to a server or 3rd party storage: AWS:S3, GridFS, DropBox, and other
react-meteor-data                 2.7.2  React hook for reactively tracking Meteor data
reactive-var                      1.0.12  Reactive variable
reywood:publish-composite         1.7.3  Publish a set of related documents from multiple collections with a reactive join
seba:minifiers-autoprefixer       2.0.1  Standard minifiers used with Meteor apps by default + css autoprefixer.
service-configuration             1.3.1  Manage the configuration for third-party services
session                           1.2.1  Session variable
shell-server                      0.5.0  Server-side component of the `meteor shell` command.
socket-stream-client              0.5.1  Provides the ClientStream abstraction used by ddp-client
standard-minifier-js              2.8.1  Standard javascript minifiers used with Meteor apps by default.
static-html                       1.3.2  Define static page content in .html files
test:lazy                         0.0.1+ summary
test:modules                      0.0.1+ summary
test:stub-validation              0.0.1+ summary
test:ts-modules                   0.0.1+ summary
tracker                           1.3.2  Dependency tracker to allow reactive callbacks
tunifight:loggedin-mixin          0.1.0  A simple logged-in and roles check mixin to use with mdg:validated-method package
typescript                        4.9.4  Compiler plugin that compiles TypeScript and ECMAScript in .ts and .tsx files
underscore                        1.0.13  Collection of small helpers: _.map, _.each, ...
zodern:types                      1.0.9  Type definitions for Meteor packages

**Comment by JorgenVatle** [comment] 2023-09-07 20:28
Do you by any chance have a local `vite-bundler` directory in your project packages directory?

**Comment by ouya99** [comment] 2023-09-07 20:31
<img width="271" alt="Screenshot 2023-09-07 at 22 31 18" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/e7c8971b-f101-4ed9-a17d-f3d30f118239">

**Comment by JorgenVatle** [comment] 2023-09-07 20:32
Remove that and you're good to go. 👍

**Comment by JorgenVatle** [comment] 2023-09-07 20:34
You should probably also remove the test packages there while you're at it. They'll only bloat your bundle with unnecessary test-specific exports. 😊 Just remember to also remove the references from your `.meteor/packages` file.

**Comment by ouya99** [comment] 2023-09-07 20:39
looking good, but new error :)

<img width="478" alt="Screenshot 2023-09-07 at 22 38 58" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/5303c727-7e75-4206-9ec3-6c5c857a171f">

**Comment by ouya99** [comment] 2023-09-07 20:42
ah react-is is part of meteor-vite.

**Comment by ouya99** [comment] 2023-09-07 20:51
`This happens because Vite serves react-is “as-is” - without transforming it anyhow and Vite relies on native modules in the browser. The “imported” file is this:

'use strict';

if ("development" === 'production') {
  module.exports = require('./cjs/react-is.production.min.js');
} else {
  module.exports = require('./cjs/react-is.development.js');
}

and as we can see this is just a CJS file.

According to the Vite docs this should be transformed during a “pre-bundle” step: https://vitejs.dev/guide/features.html#npm-dependency-resolving-and-pre-bundling

From my PoV, it looks like an issue with Vite - I’m not familiar with it enough to say what’s exactly broken. The react-is is using the very same “structure” of distributed files etc as React itself so this should just be handled in the same way - and I’m unsure why it isn’t in this case. Could you report this to the Vite team? Maybe they would have some pointers regarding this problem.`

**Comment by ouya99** [comment] 2023-09-07 21:01
https://lightrun.com/answers/algolia-react-element-to-jsx-string-the-requested-module-react-isindexjs-does-not-provide-an-export-named-forwardref

helped

**Comment by JorgenVatle** [comment] 2023-09-07 21:03
Yeah, this doesn't look like an issue with Meteor Vite unfortunately. The `react-is` dependency in the `meteor-vite` lockfile is a dev dependency, so it shouldn't be pulled in by npm when you depend on `meteor-vite`.

But it seems like you figured it out? 🙌

**Comment by ouya99** [comment] 2023-09-07 21:04
yes error after error coming in.. next one is 
<img width="452" alt="Screenshot 2023-09-07 at 23 04 09" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/c6ee2d05-bcdb-4398-bda2-229127e45ead">

**Comment by ouya99** [comment] 2023-09-07 21:06
next one
<img width="477" alt="Screenshot 2023-09-07 at 23 06 47" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/af33dd05-9d53-4fda-b09d-06e072aa041e">

**Comment by ouya99** [comment] 2023-09-07 22:32
tried adding it to main.html, no change 

`  <script type="module">
    import RefreshRuntime from 'http://localhost:3000/@react-refresh';

    RefreshRuntime.injectIntoGlobalHook(window);
    window.$RefreshReg$ = () => {};
    window.$RefreshSig$ = () => (type) => type;
    window.__vite_plugin_react_preamble_installed__ = true;
</script>`

**Comment by ouya99** [comment] 2023-09-07 22:33
i will try to setup a demo repo coming days, if i do not find a quick solution. thanks for your support!

**Comment by JorgenVatle** [comment] 2023-09-10 21:07
Alright, so seeing as the original topic for this issue should be resolved by now, let's move the discussion over to #29 as it relates to your latest issue there. 🙌

**Closed by JorgenVatle** 2023-09-10 21:07 UTC

**Comment by JorgenVatle** [comment] 2023-09-10 21:59
Just a quick update on this, using the following snippet instead, explicitly importing from Vite instead of the Meteor web server seems to resolve the issue on my end.

By default your 

```html
<script type="module">
import RefreshRuntime from "http://localhost:5173/@react-refresh" // Local Vite server created by Meteor-Vite.
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>
```

**Comment by ouya99** [comment] 2023-09-10 22:13
so this solves #29 . Great!

**Comment by ouya99** [comment] 2023-09-10 22:15
<img width="467" alt="Screenshot 2023-09-11 at 00 14 48" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/f6b5f6af-e130-4237-98e3-024beba83f2d">

got some new error :(

**Comment by JorgenVatle** [comment] 2023-09-10 22:19
Hmm.. Doesn't seem related to Meteor-Vite. Though, it suspiciously looks like a cjs/esm incompatibility. 🤔

**Comment by JorgenVatle** [comment] 2023-09-10 22:22
Oh, I could totally be wrong here though. 😅

**Comment by ouya99** [comment] 2023-09-10 22:27
<img width="466" alt="Screenshot 2023-09-11 at 00 26 53" src="https://github.com/JorgenVatle/meteor-vite/assets/2676451/f8f9b1ec-b163-4a6d-af21-23c26d0bd87c">
 
cleared cache and new error came up.
